server:
  port: 9101

spring:
  application:
    name: order-service

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka

test:
  number: 2000
