server:
  port: ${PORT:9101}

spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka

test:
  number: 9000
